name: Build and Push to Azure Container Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Cache node_modules to speed up npm ci
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            modules-

      # Install production dependencies
      - name: Install Dependencies
        run: npm ci --production

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3